const mongoose = require("mongoose");
mongoose.pluralize(null);

const ldshrmCommonEmployeeChangeCostCenterSchema = new mongoose.Schema({
    id:{
        type: String,
        unique:true,
        required: true,
    },
    empId: Number,
    specialChangeCode: Number,
    changeSerialNumber: Number,
    specialCategory: String,
    effectiveDate: String,
    oldMappingId: Number,
    oldDesignationMappingId: Number,
    oldGradeId: Number,
    oldLevelId: Number,
    oldAccommodationId: Number,
    oldStatusId: Number,
    oldJoiningDate: String,
    oldLeavesalary: Number,
    oldLeavePassage: Number,
    oldLeaveCalcDays: Number,
    oldLeaveWorkDays: Number,
    oldWorkingDaysWeek: Number,
    oldLeaveWeek: Number,
    bankId1: Number,
    bankAccountNumber1: String,
    depositAmount1: Number,
    currencyId1: Number,
    splitAccount: String,
    bankId2: Number,
    bankAccountNumber2: String,
    depositAmount2: Number,
    currencyId2: Number,
    oldTravelSectorIdFrom: Number,
    oldTravelSectorIdTo: Number,
    newGradeId: Number,
    newLevelId: Number,
    newAccommodationId: Number,
    newStatusId: Number,
    newJoiningDate: String,
    newTravelSectorIdFrom: Number,
    newTravelSectorIdTo: Number,
    endOfService: String,
    newMappingId: Number,
    newDesignationMappingId: Number,
    newLeaveSalary: Number,
    newLeavePassage: Number,
    newLeaveCalcDays: Number,
    newLeaveWorkDays: Number,
    newWorkingDaysWeek: Number,
    newLeaveWeek: Number,
    newBankId1: Number,
    newBankAccountNumber1: String,
    newCurrencyId1: Number,
    newBankId2: Number,
    newBankAccountNumber2: String,
    newCurrencyId2: Number,
    lVSalaryAmountRefund: Number,
    lVPassageAmountRefund: Number,
    gratuityAmound: Number,
    AmoundRefund0th: Number,
    remarkLine1: String,
    remarkLine2: String,
    remarkLine3: String,
    remarkLine4: String,
    eligibleForOT: String,
    freeTicketFrequency: Number,
    fareCode: String,
    dependantNumber: Number,
    maximumTickets: Number,
    ticketsEligible: Number,
    travelClass: String,
    changeRequestBy: Number,
    changeApprovedBy: Number,
    referenceDetails: String,
    updateMaster: String,
    updateTransaction: String,
    processId: String,
    dateOfUpdate: String,
    timeOfUpdate: String,
    lastActionMode: String,
    lastUser: String,
    lastWorkStation: String,
    sourceDestinationFlag: String,
    syncFlag: String,
    syncDateOfUpdate: String,
    syncTimeOfUpdate: String,
    syncProgramId: String,
    syncLastUser: String,
    syncLastWorkStation: String,
    createdById: Number,
    modifiedById: Number,
    isDeleted: Boolean,
    oldCostCenter: String,
    newCostCenter: String
},
{ timestamps: true }
);

module.exports = mongoose.model("LoginDetails",  ldshrmCommonEmployeeChangeCostCenterSchema);