const mongoose = require("mongoose");
mongoose.pluralize(null);

const ldshrmCommonEmployeeSalaryChangeSchema = new mongoose.Schema({
    salaryChangeId:{
        type: String,
        unique:true,
        required: true,
    },
    empId: Number,
    oldCountryId: Number,
    oldMappingId: Number,
    oldDesgMappingId: Number,
    oldEmpTypeId: Number,
    oldGradeId: Number,
    oldLevelId: Number,
    oldSchooling: String,
    oldTicketEligibility: String,
    oldInsurance: String,
    oldClass: String,
    oldSchoolingCount: Number,
    oldTicketCount: Number,
    oldMaritalStatus: Number,
    oldKidsCount: Number,
    oldGratuity: Number,
    oldLeavePassage: Number,
    oldAnnualLeavePsg: Number,
    oldGrossSalary: Number,
    oldCurrencyId: Number,
    newCountryId: Number,
    newMappingId: Number,
    newDesgMappingId: Number,
    newEmpTypeId: Number,
    newGradeId: Number,
    newLevelId: Number,
    newSchooling: Boolean,
    newTicketEligibility: Boolean,
    newInsurance: Boolean,
    newClass: String,
    newSchoolingCount: Number,
    newTicketCount: Number,
    newGratuity: Number,
    newLeavePassage: Number,
    newAnnualLeavePsg: Number,
    newGratuityPersis: Number,
    NewLeavePassagePersis: Number,
    newAnnualLeavePsgPersis: Number,
    newGrossSalary: Number,
    newCurrencyId: Number,
    conversionRate: Number,
    statusId: Number,
    isApproved: Boolean,
    isRejected: Boolean,
    effectiveDate: String,
    reasonId: Number,
    isBudgeted: Number,
    isInReceivingWF: Boolean,
    lastIncrementDate: String,
    annualLeaveBalance: Number,
    cutOffDate: String,
    lastWarningLetterDate: String,
    lastWarningReasonId: Number,
    previousBasic: Number,
    isSentForApproval: Boolean,
    isProcessCompleted: Boolean,
    comment: String,
    requestId: Number,
    replacedEmpId: Number,
    createdById: Number,
    createdDate: String,
    modifiedById: Number,
    modifiedDate: String,
    createdByEmpId: Number,
    modifiedByEmpId: Number,
    isDeleted: Boolean,
    businessUnitId: Number,
    departmentId: Number,
    sectionId: Number,
    designationId: Number,
    functionSkills: Number,
    gradeId: Number,
    levelId: Number,
    subSectionId: Number,
    previousBasicCurrencyId: Number,
    travelSectorID: Number,
    nationalityID: Number,
    oldCompanyType: Number,
    previousToPreviousBasicSal: Number,
    previousToPreviousBasicSalCurrency: Number,
    previousReason: String,
    previousToPreviousReason: String,
    previousToPreviousDateofIncrement: String,
    oldEmpStatusId: Number,
    newEmpStatusId: Number,
    isAdminUpdate: Boolean,
    editAdminRemark: String,
    contractStartDate: String,
    contractEndDate: String

});

module.exports = mongoose.model("LoginDetails",  ldshrmCommonEmployeeSalaryChangeSchema);